# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = 2

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define 'kafka' do |el|
    el.vm.box = "centos/7"
    el.vm.network "private_network", type: "dhcp"
  end
end
